Add type property to DeserializationOptions
k-paxian/dart-json-mapper pull request #122
Opened 2021-03-24 12:37 UTC by schultek

Resolves #121

2021-03-24 14:05 UTC, k-paxian requested changes
Nice 🙂, and with all that I would like to see a unit test as well and final code formatting using dartfmt.

2021-03-24 14:35 UTC, schultek commented
Yes, which test group would you suggest?

2021-03-24 14:40 UTC, k-paxian commented
[here ](https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/test/test.integration.dart) I guess, there obviously should be a dedicated suit for covering all `DeserializationOptions/SerializationOptions` combinations, but have no chance to introduce it yet.

2021-03-25 06:52 UTC, k-paxian approved these changes

2021-03-25 06:53 UTC, merged